version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  test-and-lint:
    executor: python/default
    docker:
      - image: cimg/python:3.11.2
    steps:
      - checkout
      - python/install-packages:
        pkg-manager: pip
      - run:
          name: lint
          command: flake8
      - run:
          name: run tests
          command: pytest
  build-and-push-dockerhub:
    docker:
      - image: cimg/python:3.11.2
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: build image
          command: docker build -t $DOCKERHUB_USERNAME/oc-lettings:0 .
      - run:
          name: log to dockerhub
          command: echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: push to dockerhub
          command: |
            docker tag $DOCKERHUB_USERNAME/oc-lettings:0 $DOCKERHUB_USERNAME/oc-lettings:$CIRCLE_SHA1
            docker push $DOCKERHUB_USERNAME/oc-lettings:$CIRCLE_SHA1

workflows:
  build-test-push-workflow:
    jobs:
      - test-and-lint
      - build-and-push-dockerhub:
          filters:
            branches:
              only: main
          requires:
            - test-and-lint